# Generated by Django 4.2 on 2023-05-25 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bas rol', 'Bas rol'), ('Esas rollar', 'Esas rollar'), ('Elave rollar', 'Elave rollar'), ('Kutlevi rollar', 'Kutlevi rollar'), ('Klip cekilisi', 'Klip cekilisi'), ('Reklam cekilisi', 'Reklam cekilisi'), ('Hamisi', 'Hamisi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Az', 'Az'), ('Rus', 'Rus'), ('Eng', 'Eng'), ('Tr', 'Tr')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Top models', 'Top models'), ('Face models', 'Face models'), ('A Class models', 'A class models'), ('Promo models', 'Promo models'), ('Photo models', 'Photo models'), ('Catwalk models', 'Catwalk models'), ('Subtive models', 'Subtive models'), ('Fitness models', 'Fitness models'), ('Hijab models', 'Hijab models')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('eyecolor', models.CharField(max_length=14)),
                ('weight', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Child', 'Child')], max_length=10)),
                ('haircolor', models.CharField(choices=[('Sari', 'Sari'), ('Qirmizi', 'Qirmizi'), ('Qara', 'Qara'), ('Kuren', 'Kuren')], max_length=14)),
                ('height', models.SmallIntegerField()),
                ('education', models.TextField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_model', models.BooleanField(default=False)),
                ('is_actor', models.BooleanField(default=False)),
                ('is_child', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(blank=True, null=True)),
                ('actorCategory', models.ManyToManyField(blank=True, related_name='actortalents', to='account.actorcategory')),
                ('modelCategory', models.ManyToManyField(blank=True, related_name='modeltalents', to='account.modelcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_premium', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(upload_to='media/covers')),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=20)),
                ('company_website', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/company')),
                ('category', models.ManyToManyField(blank=True, related_name='companies', to='account.productioncategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedn', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.ManyToManyField(related_name='languages', to='account.languages')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to='account.profile')),
            ],
            options={
                'verbose_name': 'about me',
                'verbose_name_plural': 'about_me',
            },
        ),
    ]
