# Generated by Django 4.1.7 on 2023-03-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('weight', models.PositiveSmallIntegerField()),
                ('eyecolor', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=10)),
                ('growth', models.CharField(max_length=20)),
                ('haircolor', models.CharField(max_length=14)),
                ('education', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('cv', models.FileField(upload_to='')),
                ('image1', models.ImageField(upload_to='media/images')),
                ('image2', models.ImageField(upload_to='media/images')),
                ('image3', models.ImageField(upload_to='media/images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
