# Generated by Django 4.1.7 on 2023-03-21 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='password',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
