# Generated by Django 4.1.2 on 2023-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_myuser_last_login_remove_myuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eyecolor', models.CharField(max_length=14)),
                ('weight', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('haircolor', models.CharField(max_length=14)),
                ('growth', models.SmallIntegerField()),
                ('education', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('cv', models.FileField(upload_to='')),
                ('image1', models.ImageField(upload_to='media/images')),
                ('image2', models.ImageField(upload_to='media/images')),
                ('image3', models.ImageField(upload_to='media/images')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
