# Generated by Django 4.2 on 2023-05-02 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_alter_registermessage_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('eyecolor', models.CharField(max_length=14)),
                ('weight', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('haircolor', models.CharField(max_length=14)),
                ('growth', models.SmallIntegerField()),
                ('education', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.DeleteModel(
            name='RegisterMessage',
        ),
    ]
