# Generated by Django 4.2 on 2023-05-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_category_profile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Az', 'Az'), ('Rus', 'Rus'), ('Eng', 'Eng'), ('Tr', 'Tr')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Top models', 'Top models'), ('Face models', 'Face models'), ('A Class models', 'A class models'), ('Promo models', 'Promo models'), ('Photo models', 'Photo models'), ('Catwalk models', 'Catwalk models'), ('Subtive models', 'Subtive models'), ('Fitness models', 'Fitness models'), ('Hijab models', 'Hijab models')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Top models', 'Top models'), ('Face models', 'Face models'), ('A Class models', 'A class models'), ('Promo models', 'Promo models'), ('Photo models', 'Photo models'), ('Catwalk models', 'Catwalk models'), ('Subtive models', 'Subtive models'), ('Fitness models', 'Fitness models'), ('Hijab models', 'Hijab models')], max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ActorCategory',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_me',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedn', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.ManyToManyField(related_name='lngs', to='account.languages')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(related_name='talentss', to='account.modelcategory'),
        ),
    ]
