# Generated by Django 4.2 on 2023-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_languages_modelcategory_productioncategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.AddField(
            model_name='profile',
            name='actorCategory',
            field=models.ManyToManyField(related_name='actortalents', to='account.actorcategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_actor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='modelCategory',
            field=models.ManyToManyField(related_name='modeltalents', to='account.modelcategory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Child', 'Child')], max_length=10),
        ),
    ]
