# Generated by Django 4.2 on 2023-05-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_profile_is_popular_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='growth',
            new_name='height',
        ),
    ]
