# Generated by Django 4.2 on 2023-05-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_growth_profile_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-is_premium', '-created_at']},
        ),
    ]
