# Generated by Django 4.2 on 2023-05-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_company_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actorCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='actortalents', to='account.actorcategory'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modelCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='modeltalents', to='account.modelcategory'),
        ),
    ]
