# Generated by Django 4.2 on 2023-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_actorcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorcategory',
            name='name',
            field=models.CharField(choices=[('Bas rol', 'Bas rol'), ('Esas rollar', 'Esas rollar'), ('Elave rollar', 'Elave rollar'), ('Kutlevi rollar', 'Kutlevi rollar'), ('Klip cekilisi', 'Klip cekilisi'), ('Reklam cekilisi', 'Reklam cekilisi'), ('Hamisi', 'Hamisi')], max_length=50),
        ),
    ]
