# Generated by Django 4.2 on 2023-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_about_me_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
