# Generated by Django 4.2 on 2023-05-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_profile_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='language',
            field=models.ManyToManyField(related_name='languages', to='account.languages'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to='account.profile'),
        ),
    ]
