# Generated by Django 4.2 on 2023-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_profile_actorcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='haircolor',
            field=models.CharField(choices=[('Sari', 'Sari'), ('Qirmizi', 'Qirmizi'), ('Qara', 'Qara'), ('Kuren', 'Kuren')], max_length=14),
        ),
    ]
