# Generated by Django 4.2 on 2023-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
