# Generated by Django 4.2 on 2023-05-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castingapp', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
